version: '3.2'
services:
  db:
    image: postgres:12-alpine
    container_name: db
    environment:
      POSTGRES_PASSWORD: dubidubi
      PGDATA: /data/pg
    volumes:
      - ./docker/10-init.sql:/docker-entrypoint-initdb.d/10-init.sql
      - ./docker/20-init-pgcrypto.sh:/docker-entrypoint-initdb.d/20-init-pgcrypto.sh
      - ./docker/db:/data
    restart: always
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: lucas-sandery
    ports:
      - 8080:8080
