name: Tests
on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    container: node:12
    steps:
      - name: Setup Postgres database
        uses: Daniel-Marynicz/postgresql-action@master
        with:
          postgres_image_tag: 12-alpine
          postgres_extensions: pgcrypto
          postgres_db: fund-test
          postgres_password: dubidubi

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install dependencies
        run: yarn

      - name: Generate GraphQL types
        run: yarn codegen

      - name: Setup required env variables
        run: cp .env.example .env

      - name: Run tests
        run: yarn test
        env:
          PG_HOST: localhost
          PG_PASS: dubidubi
