name: Build and Push
on:
  push:
    branches: [master]

jobs:
  build-and-push-to-gcr:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Save environment vars
        env:
          ENV_FILE: ${{ secrets.DOTENV }}
          SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}
        run: |
          echo "$ENV_FILE" | base64 -d > packages/backend/.env
          echo "$SERVICE_KEY" | base64 -d > packages/backend/service-account.json
          cp yarn.lock ./packages/backend/yarn.lock

      - uses: RafikFarhad/push-to-gcr-github-action@v3
        with:
          gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          registry: asia.gcr.io
          project_id: stiens-gate
          image_name: backend
          image_tag: ${{ github.sha }}
          context: packages/backend

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "290.0.1"
          project_id: "stiens-gate"
          service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          export_default_credentials: true

      - uses: azure/setup-kubectl@v3
      - name: Deploy
        run: |
          cd k8s/backend
          envsubst <deployment.yml >dep.tmp
          rm deployment.yml
          mv dep.tmp deployment.yml
          kubectl create secret generic pg-auth \
          --from-literal=POSTGRES_USER="postgres" \
          --from-literal=POSTGRES_PASSWORD="dubidubi" \
          --dry-run=client -o yaml >secret.yml
          gcloud container clusters get-credentials sih-closter --zone asia-southeast1-a
          kubectl apply --namespace=sih -f .
