name: Build and Push Frontend
on:
  push:
    branches: [master]

jobs:
  build-and-push-to-gcr:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Save environment vars
        run: |
          cp yarn.lock ./packages/frontend/yarn.lock

      - uses: RafikFarhad/push-to-gcr-github-action@v3
        with:
          gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          registry: asia.gcr.io
          project_id: stiens-gate
          image_name: frontend
          image_tag: ${{ github.sha }}
          context: packages/frontend

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "290.0.1"
          project_id: "stiens-gate"
          service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          export_default_credentials: true

      - uses: azure/setup-kubectl@v1
      - name: Deploy
        run: |
          cd k8s/frontend
          envsubst <deployment.yml >dep.tmp
          rm deployment.yml
          mv dep.tmp deployment.yml
          gcloud container clusters get-credentials sih-closter --zone asia-southeast1-a
          kubectl apply --namespace=sih -f .
