name: CI

on:
  push:
    branches: [ master, front-dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 13.12
    
    - name: Save key
      env:
        ACCESS_KEY: ${{ secrets.OPS_KEY_ENC }}
      run: |
        echo "$ACCESS_KEY" | base64 -d > $HOME/KEY
        chmod 400 $HOME/KEY

    - name: Install dependencies
      run: yarn install

    - name: Build
      run: |
        cd ./packages/frontend
        yarn build

    - name: Save environment vars
      env:
        ENV_FILE: ${{ secrets.ENV }}
      run: echo "$ENV_FILE" | base64 -d > $HOME/.env
    
    - name: Deploy to server
      run: |
        cd ./packages/frontend
        scp -r -i "$HOME/KEY" -o StrictHostKeyChecking=no ./build ops@url.ojaswa.com:/var/www/sih/
